services:
  stormpiper-test:
    image: gcr.io/tacoma-app/stormpiper-test:ci-test
    volumes:
      - ./stormpiper/stormpiper:/stormpiper/stormpiper
      - ./stormpiper/alembic:/stormpiper/alembic

  postgis:
    image: gcr.io/tacoma-app/postgis:ci-test

  redis:
    image: gcr.io/tacoma-app/redis:ci-test
    ports:
      - target: 6379
        published: 6379

