version: '3.7'
services:
  stormpiper-test:
    environment:
      RUN_PRESTART_MIGRATION: 1
      STP_EE_LOGIN_ON_STARTUP: false
      STP_DATABASE_URL_SYNC: "postgresql+psycopg2://docker:docker@postgis:5432/docker"
      STP_DATABASE_URL_ASYNC: "postgresql+asyncpg://docker:docker@postgis:5432/docker"
  postgis:
    build:
      context: .
      dockerfile: Dockerfile
      target: postgis
    restart: always
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5454:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:

