services:
  stormpiper-pod:
    build:
      context: .
      dockerfile: Dockerfile
      target: stormpiper-pod
    command: bash /start-reload.sh
    ports:
      - published: 8080
        target: 80

  stormpiper-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: stormpiper-test

  bg_worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: bg_worker
    command: bash /run-worker.sh

  beat_worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: bg_worker
    command: bash /run-beat.sh

  redis:
    build:
      context: .
      dockerfile: Dockerfile
      target: redis
    ports:
      - target: 6379
        published: 6379
