"""add subbasins table

Revision ID: 2986f1ba081a
Revises: 508290ea6fd4
Create Date: 2022-06-01 11:07:45.175609

"""

import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2986f1ba081a"
down_revision = "508290ea6fd4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "subbasin",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("basinname", sa.String(), nullable=True),
        sa.Column("subbasin", sa.String(), nullable=True),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                srid=2927, from_text="ST_GeomFromEWKT", name="geometry"
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("subbasin")
    # ### end Alembic commands ###
