"""add delineation relid column

Revision ID: 2e72fb6d5867
Revises: 2986f1ba081a
Create Date: 2022-06-01 11:13:09.731554

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2e72fb6d5867"
down_revision = "2986f1ba081a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tmnt_facility_delineation",
        sa.Column("relid", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tmnt_facility_delineation", "relid")
    # ### end Alembic commands ###
