"""add source controls table

Revision ID: 83958c8b9c2a
Revises: 1fe92446764f
Create Date: 2022-07-06 17:43:14.453898

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "83958c8b9c2a"
down_revision = "1fe92446764f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tmnt_source_control",
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subbasin", sa.String(), nullable=False),
        sa.Column("pollutant", sa.String(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("activity", sa.String(), nullable=False),
        sa.Column(
            "direction",
            sa.Enum("upstream", "downstream", name="direction"),
            nullable=False,
        ),
        sa.Column("percent_reduction", sa.Float(), nullable=True),
        sa.CheckConstraint("percent_reduction between 0.0 and 100.0"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("direction", "subbasin", "pollutant", "activity"),
        sa.UniqueConstraint("direction", "subbasin", "pollutant", "order"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tmnt_source_control")
    sa.Enum("upstream", "downstream", name="direction").drop(op.get_bind())
    # ### end Alembic commands ###
