"""add lgu units

Revision ID: 6ecd49718577
Revises: 37f1d46e5dc3
Create Date: 2022-07-14 15:15:43.337088

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6ecd49718577"
down_revision = "37f1d46e5dc3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lgu_load", sa.Column("units", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lgu_load", "units")
    # ### end Alembic commands ###
