"""update tracked table changes

Revision ID: 9213ee854365
Revises: 6ecd49718577
Create Date: 2022-08-01 17:33:10.645886

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9213ee854365"
down_revision = "6ecd49718577"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tmnt_facility", "updated_by")
    op.drop_column("tmnt_facility", "time_created")
    op.drop_column("tmnt_facility", "time_updated")
    op.drop_column("tmnt_facility_delineation", "updated_by")
    op.drop_column("tmnt_facility_delineation", "time_created")
    op.drop_column("tmnt_facility_delineation", "time_updated")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tmnt_facility_delineation",
        sa.Column(
            "time_created",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "tmnt_facility_delineation",
        sa.Column(
            "time_updated",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "tmnt_facility_delineation",
        sa.Column("updated_by", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "tmnt_facility",
        sa.Column(
            "time_created",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "tmnt_facility",
        sa.Column(
            "time_updated",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )

    op.add_column(
        "tmnt_facility",
        sa.Column("updated_by", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
