"""add equity fields to subbasin

Revision ID: c2304484111d
Revises: 5609bfd21d8d
Create Date: 2022-11-01 09:30:08.635467

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c2304484111d"
down_revision = "5609bfd21d8d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subbasin", sa.Column("area_acres", sa.Float(), nullable=True))
    op.add_column("subbasin", sa.Column("access", sa.Float(), nullable=True))
    op.add_column("subbasin", sa.Column("economic_value", sa.Float(), nullable=True))
    op.add_column(
        "subbasin", sa.Column("environmental_value", sa.Float(), nullable=True)
    )
    op.add_column("subbasin", sa.Column("livability_value", sa.Float(), nullable=True))
    op.add_column("subbasin", sa.Column("opportunity_value", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subbasin", "opportunity_value")
    op.drop_column("subbasin", "livability_value")
    op.drop_column("subbasin", "environmental_value")
    op.drop_column("subbasin", "economic_value")
    op.drop_column("subbasin", "access")
    op.drop_column("subbasin", "area_acres")
    # ### end Alembic commands ###
