"""add access tokens to users

Revision ID: 4177bec7971e
Revises: 284ba7ee9104
Create Date: 2022-12-30 13:00:38.159577

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4177bec7971e"
down_revision = "284ba7ee9104"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("access_token", postgresql.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "access_token")
    # ### end Alembic commands ###
