"""add globals table

Revision ID: 6af42fb28180
Revises: 4177bec7971e
Create Date: 2022-12-31 13:33:33.363410

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6af42fb28180"
down_revision = "4177bec7971e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "global_setting",
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_by", sa.String(), nullable=True),
        sa.Column("variable", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("variable"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("global_setting")
    # ### end Alembic commands ###
