"""add cost columns to tmnt attrs

Revision ID: 47e1f95064c8
Revises: 6af42fb28180
Create Date: 2022-12-31 23:07:42.656511

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "47e1f95064c8"
down_revision = "6af42fb28180"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tmnt_facility_attributes",
        sa.Column("capital_cost", sa.Float(), nullable=True),
    )
    op.add_column(
        "tmnt_facility_attributes",
        sa.Column("om_cost_per_yr", sa.Float(), nullable=True),
    )
    op.add_column(
        "tmnt_facility_attributes",
        sa.Column("lifespan_yrs", sa.Float(), nullable=True),
    )
    op.add_column(
        "tmnt_facility_attributes",
        sa.Column("replacement_cost", sa.Float(), nullable=True),
    )
    op.add_column(
        "tmnt_facility_attributes",
        sa.Column("net_present_value", sa.Float(), nullable=True),
    )

    op.execute(
        """
        DROP VIEW IF EXISTS tmnt_v;
        CREATE OR REPLACE VIEW tmnt_v AS
        SELECT
            tmnt_facility.id,
            tmnt_facility.node_id,
            tmnt_facility.altid,
            tmnt_facility.facilitytype,
            tmnt_facility.commonname,
            tmnt_facility.facilitydetail,
            tmnt_facility.flowcontrol,
            tmnt_facility.infiltrated,
            tmnt_facility.waterquality,
            tmnt_facility.flowcontroltype,
            tmnt_facility.waterqualitytype,
            tmnt_facility_attributes.basinname,
            tmnt_facility_attributes.subbasin,
            tmnt_facility_attributes.treatment_strategy,
            tmnt_facility_attributes.facility_type,
            tmnt_facility_attributes.ref_data_key,
            tmnt_facility_attributes.design_storm_depth_inches,
            tmnt_facility_attributes.tributary_area_tc_min,
            tmnt_facility_attributes.total_volume_cuft,
            tmnt_facility_attributes.area_sqft,
            tmnt_facility_attributes.inf_rate_inhr,
            tmnt_facility_attributes.retention_volume_cuft,
            tmnt_facility_attributes.media_filtration_rate_inhr,
            tmnt_facility_attributes.hsg,
            tmnt_facility_attributes.minimum_retention_pct_override,
            tmnt_facility_attributes.treatment_rate_cfs,
            tmnt_facility_attributes.depth_ft,
            tmnt_facility_attributes.captured_pct,
            tmnt_facility_attributes.retained_pct,
            tmnt_facility_attributes.capital_cost,
            tmnt_facility_attributes.om_cost_per_yr,
            tmnt_facility_attributes.lifespan_yrs,
            tmnt_facility_attributes.replacement_cost,
            tmnt_facility_attributes.net_present_value,
            GEOMETRY(tmnt_facility.geom) AS geom
        FROM tmnt_facility
        JOIN tmnt_facility_attributes ON tmnt_facility.altid = tmnt_facility_attributes.altid
    """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DROP VIEW IF EXISTS tmnt_v;
        CREATE OR REPLACE VIEW tmnt_v AS
        SELECT
            tmnt_facility.id,
            tmnt_facility.node_id,
            tmnt_facility.altid,
            tmnt_facility.facilitytype,
            tmnt_facility.commonname,
            tmnt_facility.facilitydetail,
            tmnt_facility.flowcontrol,
            tmnt_facility.infiltrated,
            tmnt_facility.waterquality,
            tmnt_facility.flowcontroltype,
            tmnt_facility.waterqualitytype,
            tmnt_facility_attributes.basinname,
            tmnt_facility_attributes.subbasin,
            tmnt_facility_attributes.treatment_strategy,
            tmnt_facility_attributes.facility_type,
            tmnt_facility_attributes.ref_data_key,
            tmnt_facility_attributes.design_storm_depth_inches,
            tmnt_facility_attributes.tributary_area_tc_min,
            tmnt_facility_attributes.total_volume_cuft,
            tmnt_facility_attributes.area_sqft,
            tmnt_facility_attributes.inf_rate_inhr,
            tmnt_facility_attributes.retention_volume_cuft,
            tmnt_facility_attributes.media_filtration_rate_inhr,
            tmnt_facility_attributes.hsg,
            tmnt_facility_attributes.minimum_retention_pct_override,
            tmnt_facility_attributes.treatment_rate_cfs,
            tmnt_facility_attributes.depth_ft,
            tmnt_facility_attributes.captured_pct,
            tmnt_facility_attributes.retained_pct,
            GEOMETRY(tmnt_facility.geom) AS geom
        FROM tmnt_facility
        JOIN tmnt_facility_attributes ON tmnt_facility.altid = tmnt_facility_attributes.altid
    """
    )

    op.drop_column("tmnt_facility_attributes", "net_present_value")
    op.drop_column("tmnt_facility_attributes", "replacement_cost")
    op.drop_column("tmnt_facility_attributes", "lifespan_yrs")
    op.drop_column("tmnt_facility_attributes", "om_cost_per_yr")
    op.drop_column("tmnt_facility_attributes", "capital_cost")
    # ### end Alembic commands ###
