"""add dsnodeid to delineation features

Revision ID: 79b569f8c17a
Revises: dad2431afc66
Create Date: 2023-01-22 11:32:08.466113

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "79b569f8c17a"
down_revision = "dad2431afc66"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tmnt_facility_delineation",
        sa.Column("ds_node_id", sa.String(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tmnt_facility_delineation", "ds_node_id")
    # ### end Alembic commands ###
