"""update cost attrs

Revision ID: c7101f4e13d9
Revises: c720aa363fc0
Create Date: 2023-04-07 23:34:43.700172

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "c7101f4e13d9"
down_revision = "c720aa363fc0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS tmnt_v")

    op.add_column(
        "tmnt_facility_cost",
        sa.Column("capital_cost_basis_year", sa.Float(), nullable=True),
    )
    op.add_column(
        "tmnt_facility_cost",
        sa.Column("om_cost_basis_year", sa.Float(), nullable=True),
    )
    op.add_column(
        "tmnt_facility_cost",
        sa.Column("install_year", sa.Float(), nullable=True),
    )
    op.add_column(
        "tmnt_facility_cost",
        sa.Column("present_value_capital_cost", sa.Float(), nullable=True),
    )
    op.add_column(
        "tmnt_facility_cost",
        sa.Column("present_value_om_cost", sa.Float(), nullable=True),
    )
    op.add_column(
        "tmnt_facility_cost",
        sa.Column("present_value_total_cost", sa.Float(), nullable=True),
    )
    op.add_column(
        "tmnt_facility_cost",
        sa.Column(
            "present_value_om_cost_table",
            postgresql.JSONB(),
            nullable=True,
        ),
    )
    op.drop_column("tmnt_facility_cost", "net_present_value")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tmnt_facility_cost",
        sa.Column("net_present_value", sa.Float(), nullable=True),
    )
    op.drop_column("tmnt_facility_cost", "present_value_om_cost_table")
    op.drop_column("tmnt_facility_cost", "present_value_total_cost")
    op.drop_column("tmnt_facility_cost", "present_value_om_cost")
    op.drop_column("tmnt_facility_cost", "present_value_capital_cost")
    op.drop_column("tmnt_facility_cost", "install_year")
    op.drop_column("tmnt_facility_cost", "om_cost_basis_year")
    op.drop_column("tmnt_facility_cost", "capital_cost_basis_year")
    # ### end Alembic commands ###
