"""cost charts

Revision ID: 50490f40801d
Revises: 0048dc98eed1
Create Date: 2023-04-19 10:13:00.968839

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "50490f40801d"
down_revision = "0048dc98eed1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column(
        "tmnt_facility_cost",
        "present_value_om_cost_table",
        new_column_name="present_value_cost_table",
        nullable=True,
    )
    op.add_column(
        "tmnt_facility_cost",
        sa.Column(
            "present_value_chart_table",
            postgresql.JSONB(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tmnt_facility_cost",
        "present_value_cost_table",
        new_column_name="present_value_om_cost_table",
        nullable=True,
    )
    op.drop_column("tmnt_facility_cost", "present_value_chart_table")
    # ### end Alembic commands ###
