"""add cost globals to tmnt_cost table

Revision ID: 413970fe67a0
Revises: 50490f40801d
Create Date: 2023-05-17 11:33:18.276106

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "413970fe67a0"
down_revision = "50490f40801d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tmnt_facility_cost",
        sa.Column("discount_rate", sa.Float(), nullable=True),
    )
    op.add_column(
        "tmnt_facility_cost",
        sa.Column("inflation_rate", sa.Float(), nullable=True),
    )
    op.add_column(
        "tmnt_facility_cost",
        sa.Column("planning_horizon_yrs", sa.Float(), nullable=True),
    )
    op.add_column(
        "tmnt_facility_cost",
        sa.Column("cost_basis_year", sa.Float(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tmnt_facility_cost", "cost_basis_year")
    op.drop_column("tmnt_facility_cost", "planning_horizon_yrs")
    op.drop_column("tmnt_facility_cost", "inflation_rate")
    op.drop_column("tmnt_facility_cost", "discount_rate")
    # ### end Alembic commands ###
