"""add subbasin fields

Revision ID: a659aaed47b9
Revises: fe5b9391ee82
Create Date: 2023-06-13 11:45:37.716609

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a659aaed47b9"
down_revision = "fe5b9391ee82"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subbasin", sa.Column("lu_resair_pct", sa.Float(), nullable=True))
    op.add_column("subbasin", sa.Column("lu_commcmu_pct", sa.Float(), nullable=True))
    op.add_column("subbasin", sa.Column("lu_rgcd_pct", sa.Float(), nullable=True))
    op.add_column("subbasin", sa.Column("lu_com_pct", sa.Float(), nullable=True))
    op.add_column("subbasin", sa.Column("lu_indh_pct", sa.Float(), nullable=True))
    op.add_column("subbasin", sa.Column("lu_indl_pct", sa.Float(), nullable=True))
    op.add_column("subbasin", sa.Column("lu_resl_pct", sa.Float(), nullable=True))
    op.add_column("subbasin", sa.Column("lu_ins_pct", sa.Float(), nullable=True))
    op.add_column("subbasin", sa.Column("lu_resm_pct", sa.Float(), nullable=True))
    op.add_column("subbasin", sa.Column("lu_resmfhd_pct", sa.Float(), nullable=True))
    op.add_column("subbasin", sa.Column("lu_comn_pct", sa.Float(), nullable=True))
    op.add_column("subbasin", sa.Column("lu_comnmu_pct", sa.Float(), nullable=True))
    op.add_column("subbasin", sa.Column("lu_os_pct", sa.Float(), nullable=True))
    op.add_column("subbasin", sa.Column("lu_shore_pct", sa.Float(), nullable=True))
    op.add_column("subbasin", sa.Column("lu_rgctm_pct", sa.Float(), nullable=True))
    op.add_column("subbasin", sa.Column("lc_pasture_pct", sa.Float(), nullable=True))
    op.add_column("subbasin", sa.Column("lc_grass_pct", sa.Float(), nullable=True))
    op.add_column("subbasin", sa.Column("lc_water_pct", sa.Float(), nullable=True))
    op.add_column("subbasin", sa.Column("lc_imp_roof_pct", sa.Float(), nullable=True))
    op.add_column(
        "subbasin", sa.Column("lc_imp_nonroof_pct", sa.Float(), nullable=True)
    )
    op.add_column("subbasin", sa.Column("lc_imp_total_pct", sa.Float(), nullable=True))
    op.add_column(
        "subbasin",
        sa.Column("age_of_development_score", sa.Float(), nullable=True),
    )
    op.add_column(
        "subbasin",
        sa.Column("pavement_condition_score", sa.Float(), nullable=True),
    )
    op.add_column("subbasin", sa.Column("biodiversity_pct", sa.Float(), nullable=True))
    op.add_column("subbasin", sa.Column("urban_heat_degc", sa.Float(), nullable=True))
    op.add_column(
        "subbasin",
        sa.Column("discharge_points_count", sa.Float(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subbasin", "discharge_points_count")
    op.drop_column("subbasin", "urban_heat_degc")
    op.drop_column("subbasin", "biodiversity_pct")
    op.drop_column("subbasin", "pavement_condition_score")
    op.drop_column("subbasin", "age_of_development_score")
    op.drop_column("subbasin", "lc_imp_total_pct")
    op.drop_column("subbasin", "lc_imp_nonroof_pct")
    op.drop_column("subbasin", "lc_imp_roof_pct")
    op.drop_column("subbasin", "lc_water_pct")
    op.drop_column("subbasin", "lc_grass_pct")
    op.drop_column("subbasin", "lc_pasture_pct")
    op.drop_column("subbasin", "lu_rgctm_pct")
    op.drop_column("subbasin", "lu_shore_pct")
    op.drop_column("subbasin", "lu_os_pct")
    op.drop_column("subbasin", "lu_comnmu_pct")
    op.drop_column("subbasin", "lu_comn_pct")
    op.drop_column("subbasin", "lu_resmfhd_pct")
    op.drop_column("subbasin", "lu_resm_pct")
    op.drop_column("subbasin", "lu_ins_pct")
    op.drop_column("subbasin", "lu_resl_pct")
    op.drop_column("subbasin", "lu_indl_pct")
    op.drop_column("subbasin", "lu_indh_pct")
    op.drop_column("subbasin", "lu_com_pct")
    op.drop_column("subbasin", "lu_rgcd_pct")
    op.drop_column("subbasin", "lu_commcmu_pct")
    op.drop_column("subbasin", "lu_resair_pct")
    # ### end Alembic commands ###
