"""add capacity rank to subbasins

Revision ID: 452744bc099f
Revises: a659aaed47b9
Create Date: 2023-07-25 15:28:14.718344

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "452744bc099f"
down_revision = "a659aaed47b9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("subbasin", sa.Column("capacity_rank", sa.Float(), nullable=True))
    op.add_column("subbasin", sa.Column("rankcriteria", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subbasin", "capacity_rank")
    op.drop_column("subbasin", "rankcriteria")
    # ### end Alembic commands ###
