"""add ddt to tmnt attr

Revision ID: 4c54e753599b
Revises: 452744bc099f
Create Date: 2023-08-18 22:57:02.394645

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4c54e753599b"
down_revision = "452744bc099f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tmnt_facility_attribute",
        sa.Column("treatment_drawdown_time_hr", sa.Float(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tmnt_facility_attribute", "treatment_drawdown_time_hr")
    # ### end Alembic commands ###
