from datetime import datetime
from typing import Any
from uuid import UUID

from geojson_pydantic import Feature, FeatureCollection, Point, Polygon
from nereid.models.treatment_facility_models import STRUCTURAL_FACILITY_TYPE
from pydantic import Field, field_validator

from .base import BaseModel, BaseORM
from .tmnt_attr import TMNTFacilityPatch


class DelineationProps(BaseModel):
    name: None | str = None
    relid: None | str = None


class DelineationPropsUpdate(DelineationProps):
    """these props are autogenerated by the validator function."""

    altid: None | str = None
    node_id: None | str = None
    area_acres: None | float = None


def lower_precision(data: list, precision=5) -> None:
    for obj in data:
        if isinstance(obj, tuple):
            obj = list(obj)

        if isinstance(obj, float):
            obj = round(obj, precision)
        elif all(isinstance(v, float) for v in obj):
            for i, v in enumerate(obj):
                obj[i] = round(v, precision)
        else:
            lower_precision(obj)


class LowResPolygon(Polygon):
    @field_validator("coordinates", mode="before")
    def low_precision(cls, coordinates: list) -> list:
        """limit polygon precision."""
        for ele in coordinates:
            lower_precision(ele)
        return coordinates


class LowResPoint(Point):
    @field_validator("coordinates", mode="before")
    def low_precision(cls, coordinates: list) -> list:
        """limit point precision."""
        coordinates = list(coordinates)
        for ele in [coordinates]:
            lower_precision(ele)
        return coordinates


DelineationFeatureCollection = FeatureCollection[
    Feature[LowResPolygon, DelineationProps]
]
DelineationFeatureCollectionUpdate = FeatureCollection[
    Feature[LowResPolygon, DelineationPropsUpdate]
]

StructuralFacilityFeatureCollection = FeatureCollection[
    Feature[LowResPoint, dict[str, Any] | TMNTFacilityPatch | STRUCTURAL_FACILITY_TYPE]
]

DELIN_BBOX_COORD_01 = [
    [
        [-122.473, 47.250],
        [-122.466, 47.250],
        [-122.466, 47.255],
        [-122.473, 47.255],
        [-122.473, 47.250],
    ]
]

TMNT_PROPERTIES_BMP_01 = {
    "node_id": "bmp-01",
    "facility_type": "bioretention_with_partial_infiltration_simple",
    "captured_pct": 80,
    "retained_pct": 20,
}

TMNT_PROPERTIES_BMP_01_COST = {
    **TMNT_PROPERTIES_BMP_01,
    **{
        "capital_cost": 250000,
        "om_cost_per_yr": 6000,
        "lifespan_yrs": 30,
        "replacement_cost": 180000,
    },
}


DELIN_ONLY = {
    "delineation_collection": {
        "type": "FeatureCollection",
        "features": [
            {
                "type": "Feature",
                "properties": {"name": "delin-01"},
                "geometry": {
                    "type": "Polygon",
                    "coordinates": DELIN_BBOX_COORD_01,
                },
            }
        ],
    }
}

TMNT_ONLY = {
    "tmnt_facility_collection": {
        "type": "FeatureCollection",
        "features": [
            {
                "type": "Feature",
                "properties": TMNT_PROPERTIES_BMP_01_COST,
                "geometry": {
                    "type": "Point",
                    "coordinates": [-122.473, 47.255],
                },
            },
        ],
    },
}

TMNT_ONLY_NO_COST = {
    "tmnt_facility_collection": {
        "type": "FeatureCollection",
        "features": [
            {
                "type": "Feature",
                "properties": TMNT_PROPERTIES_BMP_01,
                "geometry": {
                    "type": "Point",
                    "coordinates": [-122.473, 47.255],
                },
            },
        ],
    },
}

DELIN_TO_TMNT = {
    "delineation_collection": {
        "type": "FeatureCollection",
        "features": [
            {
                "type": "Feature",
                "properties": {
                    "name": "delin-01",
                    "relid": "bmp-01",
                },
                "geometry": {
                    "type": "Polygon",
                    "coordinates": DELIN_BBOX_COORD_01,
                },
            },
            {
                "type": "Feature",
                "properties": {
                    "name": "delin-02",
                    "relid": "bmp-01",
                },
                "geometry": {
                    "type": "Polygon",
                    "coordinates": DELIN_BBOX_COORD_01,
                },
            },
        ],
    },
    **TMNT_ONLY,
}

DELIN_ONLY_SCENARIO = {"name": "delin only", "input": DELIN_ONLY}
TMNT_ONLY_SCENARIO = {"name": "tmnt only", "input": TMNT_ONLY}
TMNT_SCENARIO = {"name": "tmnt scenario", "input": DELIN_TO_TMNT}
TMNT_SCENARIO_NO_COST = {
    "name": "tmnt scenario no cost",
    "input": {**DELIN_TO_TMNT, **TMNT_ONLY_NO_COST},
}

SCENARIO_EXAMPLES = {
    "empty": {"summary": "", "value": {"name": "empty scenario"}},
    "delin only": {"summary": "", "value": DELIN_ONLY_SCENARIO},
    "tmnt only": {"summary": "", "value": TMNT_ONLY_SCENARIO},
    "delin to tmnt": {"summary": "", "value": TMNT_SCENARIO},
}


class ScenarioInput(BaseModel):
    # if none, validate tmnt facility and do cost analysis. all wq tables are none.
    delineation_collection: DelineationFeatureCollection | None = None

    # if none, compute load from delineation. all wq tables are none.
    tmnt_facility_collection: StructuralFacilityFeatureCollection | None = None


class ScenarioInputUpdate(BaseModel):
    # if none, validate tmnt facility and do cost analysis. all wq tables are none.
    delineation_collection: DelineationFeatureCollectionUpdate | None = None

    # if none, compute load from delineation. all wq tables are none.
    tmnt_facility_collection: StructuralFacilityFeatureCollection | None = None


class ScenarioBase(BaseModel):
    name: str | None = "unnamed"
    info: dict | None = Field(
        None,
        description=(
            "Any associated data object to store with the project. "
            "Frontend can determine the keys and values of this object."
        ),
    )
    input: ScenarioInput | None = None


class ScenarioPost(ScenarioBase): ...


class ScenarioPatch(ScenarioBase): ...


class ScenarioUpdate(ScenarioPatch):
    updated_by: str | None = None
    input: ScenarioInputUpdate | None = None
    input_time_updated: datetime | None = None
    loading_hash: str | None = None
    input_hash: str | None = None
    structural_tmnt: list[dict] | None = None
    result_time_updated: datetime | None = None
    lgu_boundary: dict | None = None
    lgu_load: list[dict] | None = None
    delin_load: list[dict] | None = None
    graph_edge: list[dict] | None = None
    structural_tmnt_result: list[dict] | None = None


class ScenarioSolve(ScenarioUpdate):
    id: UUID


class ScenarioCreate(ScenarioBase):
    created_by: str | None = None
    updated_by: str | None = None
    input: ScenarioInputUpdate | None = None
    input_time_updated: datetime | None = None
    loading_hash: str | None = None
    input_hash: str | None = None
    structural_tmnt: list[dict] | None = None


# Properties shared by models stored in DB
class ScenarioInDBBase(BaseORM, ScenarioUpdate):
    id: UUID
    created_by: str | None = None
    time_created: datetime | None = None
    time_updated: datetime | None = None


# Properties to return to client
class Scenario(ScenarioInDBBase): ...
