apiVersion: v1
kind: Service
metadata:
  name: traefik
  labels:
    app: traefik
spec:
  # externalTrafficPolicy: Local
  loadBalancerIP:  "34.110.225.142"
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: web
      port: 8000
      # targetPort: 8080
    - protocol: TCP
      name: admin
      port: 8080
      # targetPort: 9080
    - protocol: TCP
      name: websecure
      port: 4443
      # targetPort: 4443
  selector:
    app: traefik

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: traefik
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v2.7
          args:
            - --api.insecure
            - --accesslog
            - --entrypoints.web.Address=:8000
            - --entrypoints.websecure.Address=:4443
            # - --entrypoints.admin.Address=:8080
            # Uncomment the below lines to redirect http requests to https.
            # This specifies the port :443 and not the https entrypoint name for the
            # redirect as the service is listening on port 443 and directing traffic
            # to the 8443 target port. If the entrypoint name "websecure" was used,
            # instead of "to=:443", then the browser would be redirected to port 8443.
            # - --entrypoints.web.http.redirections.entrypoint.to=:443
            # - --entrypoints.web.http.redirections.entrypoint.scheme=https
            - --providers.kubernetescrd
            - --providers.kubernetescrd.allowCrossNamespace=true
            - --providers.kubernetesingress
            - --certificatesresolvers.myresolver.acme.tlschallenge
            - --certificatesresolvers.myresolver.acme.email=aorr@geosyntec.com
            - --certificatesresolvers.myresolver.acme.storage=acme.json
            # Please note that this is the staging Let's Encrypt server.
            # Once you get things working, you should remove that whole line altogether.
            - --log.level=DEBUG
            - --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
            - --ping
            # - --ping.entryPoint=web
            # readinessProbe:
            #   httpGet:
            #     path: /ping
            #     port: 80
          # livenessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     path: /ping
          #     port: 9080
          #     scheme: HTTP
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          #   timeoutSeconds: 3
          ports:
            - name: web
              containerPort: 8000
            - name: websecure
              containerPort: 4443
            - name: admin
              containerPort: 8080
