
= Tacoma Watershed Insights 
== Parameter Dictionary

link:#altid[altid]

=== Treatment Facility Input Parameters

[[facility_type]]

Facility Type::
  TODO

=== Result Parmeters

[[altid]]

altid::
  TODO

[[area_sqft]]

area_sqft::
  TODO

[[captured_pct]]

captured_pct::
  TODO

[[commonname]]

commonname::
  TODO

[[depth_ft]]

depth_ft::
  TODO

[[design_storm_depth_inches]]

design_storm_depth_inches::
  TODO

[[facility_type]]

facility_type::
  TODO

[[facilitydetail]]

facilitydetail::
  TODO

[[facilitytype]]

facilitytype::
  TODO

[[flowcontrol]]

flowcontrol::
  TODO

[[flowcontroltype]]

flowcontroltype::
  TODO

[[hsg]]

hsg::ope
  TODO

[[inf_rate_inhr]]

inf_rate_inhr::
  TODO

[[infiltrated]]

infiltrated::
  TODO

[[media_filtration_rate_inhr]]

media_filtration_rate_inhr::
  TODO

[[minimum_retention_pct_override]]

minimum_retention_pct_override::
  TODO

[[node_id]]

node_id::
  TODO

[[retained_pct]]

retained_pct::
  TODO

[[retention_volume_cuft]]

retention_volume_cuft::
  TODO

[[total_volume_cuft]]

total_volume_cuft::
  TODO

[[treatment_rate_cfs]]

treatment_rate_cfs::
  TODO

<div id

waterqualitytype | |

Table: Treatment Facility Parameters

[cols=",",options="header",]
|===
|Parameter |Description
|capital_cost |None
|capital_cost_basis_year: int |None
|om_cost_per_yr: float |None
|om_cost_basis_year: int |float
|install_year: int |float
|replacement_cost: float |None
|lifespan_yrs: float |int
|===

== Cost Analysis Parameters

=== Global Parameters

....
discount_rate: float | None = None
inflation_rate: float | None = None
planning_horizon_yrs: float | int | None = None
cost_basis_year: float | int | None = None
....

=== Input Parameters

....
# cost results
present_value_capital_cost: float | None
present_value_om_cost: float | None
present_value_total_cost: float | None
present_value_cost_table: list[dict] | None = None
present_value_chart_table: list[dict] | None = None

# cost effectiveness
TCu_total_cost_dollars_per_load_lbs_removed: float | None
TN_total_cost_dollars_per_load_lbs_removed: float | None
TP_total_cost_dollars_per_load_lbs_removed: float | None
TSS_total_cost_dollars_per_load_lbs_removed: float | None
TZn_total_cost_dollars_per_load_lbs_removed: float | None
PHE_total_cost_dollars_per_load_lbs_removed: float | None
PYR_total_cost_dollars_per_load_lbs_removed: float | None
DEHP_total_cost_dollars_per_load_lbs_removed: float | None
....

....
"node_id",
"epoch",
"node_type",
"ntype",
"facility_type",
"valid_model",
"subbasin",
"basinname",
....

== Shared properties

class TMNTFacilityAttrBase(BaseModel): # modeling attrs facility_type: None | str = None hsg: None | str = None design_storm_depth_inches: None | float = None tributary_area_tc_min: None | float = None total_volume_cuft: None | float = None area_sqft: None | float = None inf_rate_inhr: None | float = None retention_volume_cuft: None | float = None media_filtration_rate_inhr: None | float = None minimum_retention_pct_override: None | float = None treatment_rate_cfs: None | float = None depth_ft: None | float = None

....
# simplified attrs
captured_pct: None | float = None
retained_pct: None | float = None
....

captured_pct 1::
  Definition 1
retained_pct::
  Percentage retained _(cu/ft)_

== Introduction

This manual describes how to use the Tacoma Watershed Insights web application. This application lets users track stormwater infrastructure, assess performance, and make informed decisions regarding stormwater and water quality in Tacoma.

=== Purpose

TODO

This is a Warning

*Note*

This is a Note

____
*Note* This is a note
____

____
*Warning* This is a warning
____

=== Key Concepts

==== Facility IDs

==== Subbasins

==== Scenarios

==== Climate Epochs

==== Facility Types

==== Facility Modeling Parameters

==== Simple vs. Detailed Facilities

==== Pollutants

== System Administration

=== Sign Up as a New User

You must register and be approved as a new user before using the site. To sign up, click *Login* in the upper right hand corner of the site. At the login page, click *Register* to be taken to the registration page. After entering the required details, click *Submit* to create your account. An email will be sent to your provided email address for verification.

Before you can access the site, your account must be approved by a User Admin. See the Modifying User Roles section for information on approving new users.

=== User Roles

Users can have one of the following roles associated with their account.

Only a User Admin or System Admin may edit user roles.

.Roles and Permissions
[width="100%",cols="32%,68%",options="header",]
|===
|Role |Permissions
|Public |None
|Read-only |Read access to data via site and via token
|User/Editor |All of the above, plus • access to scenarios and editing data
|User Admin |All of the above, plus • access to user manager • access to application settings
|System Admin |All of the above, plus • direct api access
|===

=== Managing Users

Only a User Admin or System Admin may edit user roles. To approve new users and to update user roles, follow these steps.

[arabic]
. Click on your profile avatar in the upper left-hand corner of the screen.
. Select *Manage Users* from the menu.

You will be taken to the Manage Users page, where you can edit and save user role information.

== Viewing Results with the Map Explorer

The map explorer module is the main access point for all the spatial resources that can be used to view existing infrastructure and water quality conditions.

=== Viewing Layers

By default, the following layers are enabled:

* Stormwater facilities
* Stormwater facility delineations
* Stormwater subbasins

To view other layers select the layer icon on the left-hand menu. A new panel will display with available layers.

Other layers that can be viewed are:

*Conveyance*

* Catchbasin Leads
* Regional Facility Model: Manholes
* Surfacewater Inlet
* Surfacewater Main
* Surfacewater Trunk

*Landcover and Landuse*

* Land Cover Category
* Imperviousness
* Contours
* Runoff
* Terrain

*Pollutants*

* Total Copper Concentration
* Total Nitrogen Concentration
* Total Suspended Solids (TSS) Concentration
* Total Zinc Concentration

=== Viewing Facility Overview Information

You can view summary information for a particular BMP by clicking on it from the Map Explorer. The map will zoom to the selected facility and a panel will be displayed showing the following information:

* ALTID
* Faciliy Type
* Common Name
* Flow Control Type
* Water Quality Type
* Basin Name
* Subbasin

=== Viewing Facility Details

Click on *View Facility Details* from the Facility Overview Panel to see and edit particular facility attribues. In addition to the overview information displayed on the Map Explorer you can view water quality parameters, cost analysis parameters, and detailed performance data.

=== Exporting Facility Details

To export detailed facility data, click on *Export Results* from the Facility Detail Page. This will export a `.csv` file with all facility attributes and peformance results.

=== Searching for a Facility

To search for a particular facility, select the search icon on the left*hand toolbar. A panel will appear with search options. You may search by the following categories:

* *altid/node_id* - Facility Type, or Facility
* *Facility Type* Refers to the City designated facility type
* *Facility Type (WQ Modeling)* - Refers to the facility type designation used for water quality modeling

== Using the BMP Facility Results View

The BMP Facility Results View can be used to view a summary of the performance of existing BMP’s. To access the viewer, select *WQ Results Viewer* from the dropdown menu at the top menu bar, or from the homepage.

You can view individual BMP results by selecting the *BMP Facility Results View* card or by selecting the icon on the left-hand menu bar.

Results are summarized by climate epoch. The tables below describe the items associated with facility results.

=== Overview Tab

.Facility Overview parameters
[width="100%",cols="50%,50%",options="header",]
|===
|Name |Description
|Facility Type |Facility type used for water quality modeling
|Node Type |Modeled type (Simple Facility, Volume-based Facility, or Flow Based Facility)
|Captured Pct |How much runoff is captured by the facility annually.
|Treated Pct |How much runoff is treated by the facility annually.
|Retained Pct |How much runoff is retained or infiltrated by the facility annually.
|Retained Pct |How much runoff is bypassed by the facility annually.
|===

=== Runoff Stats Tab

.Runoff Stats Parameters
[width="100%",cols="50%,50%",options="header",]
|===
|Name |Description
|Runoff Volume Cuft Inflow |Annual influent volume to the facility _(ft3/yr)_
|Runoff Volume Cuft Treated |Annual volume that is treated by the facility _(ft3/yr)_
|Runoff Volume Cuft Retained |Annual volume that is retained or infiltrated by the facility _(ft3/yr)_
|Runoff Volume Cuft Captured |Annual volume that is captured by the facility _(ft3/yr)_
|Runoff Volume Cuft Bypassed |Annual influent volume that is bypassed by the facility _(ft3/yr)_
|===

=== Pollutant Mass Flow Tab

.Pollutant Mass Flow Parameters
[width="100%",cols="50%,50%",options="header",]
|===
|Name |Description
|Tss Load Lbs Inflow |Total Suspended Solids load entering the facility _(lbs/yr)_
|Tss Load Lbs Removed |Total Suspended Solids removed by the facility _(lbs/yr)_
|Tn Load Lbs Inflow |Total Nitrogen load entering the facility _(lbs/yr)_
|Tn Load Lbs Removed |Total Nitrogen removed by the facility _(lbs/yr)_
|Tp Load Lbs Inflow |Total Phosphorus load entering the facility _(lbs/yr)_
|Tp Load Lbs Removed |Total Phosphorus removed by the facility _(lbs/yr)_
|Tzn Load Lbs Inflow |Total Zinc Load entering the facility _(lbs/yr)_
|Tzn Load Lbs Removed |Total Zinc removed by the facility _(lbs/yr)_
|Tcu Load Lbs Inflow |Total Copper load entering the facility _(lbs/yr)_
|Tcu Load Lbs Removed |Total Copper removed by the facility _(lbs/yr)_
|===

=== Pollutant Concentration Tab

.Pollutant Concentration Parameters
[width="100%",cols="50%,50%",options="header",]
|===
|Name |Description
|Tss Conc Mg/L Influent |Average annual Total Suspended Solids influent concentration _(mg/L)_
|Tss Conc Mg/L Effluent |Average annual Total Suspended Solids effluent concentration _(mg/L)_
|Tn Conc Mg/L Influent |Average annual Total Nitrogen influent concentration _(mg/L)_
|Tn Conc Mg/L Effluent |Average annual Total Nitrogen effluent concentration _(mg/L)_
|Tp Conc Mg/L Influent |Average annual Total Phosphorus influent concentration _(mg/L)_
|Tp Conc Mg/L Effluent |Average annual Total Phosphorus effluent concentration _(mg/L)_
|Tzn Conc Ug/L Influent |Average annual Total Zinc influent concentration _(μg/L)_
|Tzn Conc Ug/L Effluent |Average annual Total Zinc effluent concentration _(μg/L)_
|Tcu Conc Ug/L Influent |Average annual Total Copper influent concentration _(μg/L)_
|Tcu Conc Ug/L Effluent |Average annual Total Copper effluent concentration _(μg/L)_
|===

== Using the Subbasins Results View

The water quality results viewer can be used to view the conditions of each stormwater subbasin. To access the viewer, select it from the dropdown menu at the top menu bar, or from the homepage.

You can view aggregated results by subbasin by selecting the *Subbasin Results View* card or by selecting the icon on the left-hand menu bar. To view a chloropleth map of results, select the parameter to visualize from the menu next to the map.

=== Exporting Results

To export results from the Subbasin Results View, click the *Export* button on the table below the map. This will download a CSV file of all results. To export a selection of data, select the rows you want to export on the table, then click *Export*.

=== Available Data Layers

.Available Data Layers in the Subbasin Results View
[width="100%",cols="34%,33%,33%",options="header",]
|===
|Name |Description |Data Source
|Land Use Breakdown |Percent Land Use Category in Subbasin |Tacoma ArcGIS REST API: Land Use Designations `(General/LandUseDesignations/MapServer/0)`
|Land Cover Breakdown |Percent Land Cover Category in Subbasin |https://www.stormwaterheatmap.org/docs/Data%20Layers/land_cover[TNC Stormwater Heatmap]
|Runoff |Runoff depth, runoff volume, total volume reduced by stormwater facilities. |Calculated
|Treatment Facility Summary |Number of BMPs, Treated Area, Area Treated by Basic Water Quality BMPs, Area Treated by Flow Control BMPs, Effective Area |Calculated
|Average Pollutant Washoff Concentration |Average Annual Concentration before treatment |Calculated
|Annual Load Reductions |Average Annual Pollutant Load reductions from BMPs |Calculated
|===

== Editing Facility Data

=== Editing Water Quality Parameters

You can edit the parameters used to model facilities in the *Facility Details* view. There are several ways to navigate to this view:

* From the Map Explorer map, click on a facility to open the Facility Overview panel. Then, click on *View Facility Details* to be taken to the detail page.
* From the *Water Quality Results Viewer,* click on a BMP name in the table.

=== Updating from Simple to Detailed Facility

By default, most facilities are modeled as simple facilities, meaning only two parameters are used: link:#captured_pct[Captured Percentage], and link:retained_pct[Retained Percentage]. The Simple Facility type should be used when detailed data about a facility are not available (e.g. the facility’s infiltration area).

If more detailed data are available, turn off the Simple Facility switch, and parameters specific to the facility type will be editable.

=== Editing Facility Type

If a link:#facility_type[Facility Type] needs to be updated, select the Facility Type dropdown menu and choose the appropriate facility type. Click *Save* to save your edits.

*Warning* Saving your edits does not recalculate results. To recalculate, click the *Refresh Results* button on the Facility Details Page.

=== Editing Life Cost Analysis Parameters

By default, facilities will not have cost parameters unless users provide cost analysis parameters. Facilities without cost data will show the following message under the Lifecycle Cost Analysis Heading:

____
_Lifecycle costs are unavailable for this facility._ _This usually means that the ``Cost Analysis Parameters'' are incomplete._
____

To edit lifecycle cost parameters, select the dropdown menu titled *Cost Analysis Parameters.* There, you can enter the cost analysis parameters directly for a facility. See the link:#cost_analysis_params[Cost Analysis Parameters section] for descriptions of parameters.

==== King County Cost Estimator Tool

To assist with selection of cost analysis parameters, a cost estimator tool is available; it uses cost curves developed by King County for various facilities. To use this tool, click on the *King County Cost Esimator Tool* from a BMP Facility Details Page. This will open a dialog box to select and apply data from King County cost curves.

First, select the appropriate facility type under the _BMP Type_ dropdown menu. This will preselect an appropriate BMP Cost Curve used by King County (_KC BMP Variation_ in the tool). You can refine or change the selected cost curve under the __KC BMP Variation” menu. Cost curves that match the selected __BMP Type* will be shown in *bold*.

In order to calculate the cost parameters, you must enter a sizing parameter in the next dialog box. Depending on the cost curve selected, the dialog box will display either _area (sqft)_ or _each (count)._ Here, _area_ refers to the footprint area of a facility (e.g. the total area of pervious pavement), or the number of facilities to be installed (e.g. number of UIC wells).

After entering the a number denoting the area or number of facilities, the Capital Cost and O&M Costs will be calculated. Click _Apply to BMP Form_ to apply the calculated costs to the facility. To calculate the final lifecycle cost, you will need to enter data for the following:

*Install Year* - The year of installation, denoting what year to apply the capital costs.

*Replacement Cost* - The cost to replace a facility. This cost is intended to reflect costs related to major replacement of facility components, such as replacement of soil after multiple years of use.

*Lifespan Yrs* - How long the facility would be operated before replacement would be necessary.

### Global Cost Settings In order to calculate lifecycle costs the same way for every facility, the tool uses four global cost parameters (_discount rate_, _inflation rate_, _planning horizon_, and _cost basis year_). These parameters apply to all facilities analyzed, instead of a particular facility.

To edit these global parameters, select _Settings_ under your user profile in the top left portion of the screen. Individual cost parameters can be edited by clicking the edit tool to the left of each parameter name.

== Using the Prioritization Module

The watershed prioritization module allows users to identify and prioritize areas for actions to meet watershed planning goals related to water quality, habitat, and social equity.

=== Selecting Project Type

The _Project Type_ dialog denotes what type of project is being considered. The two choices are:

* *Retrofit* - Projects that are intended to improve water quality or hydrology. This choice gives a higher priority to subbasins that have a higher pollutant load, or do not have adequate stormwater infrastructure.
* *Preservation* - Projects that are intended to preserve an area in a subbasin with better water quality or already have adequate stormwater infrastructure.

=== Setting Priority Weights

The prioritization tool allows users to weight watershed management goals based on their relative importance. Weights are positive numbers

Weights can be zero or any positive number, and reflect a decision maker or stakeholders preferences. The higher the weight, the more important the criterion. Numerically, this represents a factor of preference. For example if Goal A has a weight of 1 and Goal B has a weight of 2, Goal B will be treated as twice as important as Goal A.

No constraints have been set on the scale of weights, however, it is common practice to set a total number of weighting points (e.g. 10 points) and assign weights so that the sum of weights is equal to this predetermined total.

Priority weights are assigned for each major watershed goal. Goals are comprised of subbgoals and numeric metrics as described below:

*Goal 1: Improve Water Quality Outcomes (Clean Water Goal)*

[width="100%",cols="45%,55%",options="header",]
|===
|*Sub-goal* |*Criteria*
|1.1 Prioritize areas based on pollutant concentrations |Total Nitrogen Concentration TSS Concentration Annual Runoff Imperviousness
|1.2 Improve infrastructure in areas with inadequate stormwater management |Percent of Area Treated Age of Development
|===

*Goal 2: Increase Resilience to Climate Change Impacts (Resilient Community Goal)*

[width="100%",cols="50%,50%",options="header",]
|===
|*Sub-goal* |*Criteria*
|2.1 Target areas most vulnerable to and at risk for climate change impacts |Urban Heat Island Capacity Issues Layer
|===

*Goal 3: Preserve and Restore Critical and Sensitive Habitat (Healthy Ecosystems)* | *Sub-goal* | *Criteria* | | ———— | ———— | 3.1 Preserve and improve Natural Spaces | ES Open Space/Natural Resource Areas Biodiversity Corridors

*Goal 4: Implement Equity and Social Justice (Healthy Neighborhoods; Equity)* | *Sub-goal* | *Criteria* | | ———— | ———— | 4.1 Prioritize areas of overlapping equity needs as identified by other Tacoma programs |Equity Index Score Livability Index| 4.2 Improve access to safe, high-quality roadway infrastructure (green infrastructure recommendation) | Pavement Condition Index|

Table: Watershed Planning Goals used in the Prioritization Module.

=== Viewing Prioritization Results

After selecting and submitting priority weights, results will be shown on the chlorlopleth map and in the _Subbasin Prioritization Results_ table.

Subbasins with higher priority scores reflect a higher preference for new projects based on user weighting. Clicking on a row will highlight the selected subbasin on the map.

=== Downloading Prioritization Results

To understand the breakdown of attributes and weights from the prioritization module, download the results by clicking on the _Export_ button. This will download a .CSV file listing subgoals, criteria, weights, direction of criteria (wether a criteria should be minimized or maximized), as well as the criterion-specific results.
