apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: worker
  labels:
    app: stormpiper

spec:
  replicas: 1
  selector:
    matchLabels:
      app: stormpiper
  template:
    metadata:
      labels:
        app: stormpiper
    spec:
      containers:
        - name: worker
          image: gcr.io/tacoma-app/bg_worker
          resources:
            requests:
              memory: 512Mi
              cpu: 100m
            limits:
              memory: 2Gi
              cpu: 1000m
          command:
            - /run-worker.sh
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: prod-secrets

---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: worker
spec:
  targetRef:
    kind: Deployment
    name: worker-prod
    apiVersion: apps/v1
  updatePolicy:
    updateMode: Off
  resourcePolicy:
    containerPolicies:
      - mode: 'Auto'
        containerName: '*'
