apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: worker
  labels:
    app: stormpiper

spec:
  replicas: 1
  selector:
    matchLabels:
      app: stormpiper
  template:
    metadata:
      labels:
        app: stormpiper
    spec:
      containers:
        - name: worker
          image: gcr.io/tacoma-app/bg_worker
          resources:
            requests:
              memory: 1500Mi
              cpu: 250m
            limits:
              memory: 2Gi
              cpu: 500m
          command:
            - /run-worker.sh
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: prod-secrets
