apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: beat
  labels:
    app: stormpiper

spec:
  replicas: 1
  selector:
    matchLabels:
      app: stormpiper
  template:
    metadata:
      labels:
        app: stormpiper
    spec:
      containers:
        - name: beat
          image: gcr.io/tacoma-app/bg_worker
          resources:
            requests:
              memory: 256Mi
              cpu: 50m
          command:
            - /run-beat.sh
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: prod-secrets

---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: beat
spec:
  targetRef:
    kind: Deployment
    name: beat-prod
    apiVersion: apps/v1
  updatePolicy:
    updateMode: Off
  resourcePolicy:
    containerPolicies:
      - mode: 'Auto'
        containerName: '*'
