name: Manual Deployment

on:
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Alternative option - authentication via credentials json
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_JSON_KEY }}'
      
      # Setup gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        
      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |
          # replacing the image name in the k8s template
          kubectl get pods -o wide
        
