name: Build and Push Image to GCR

on:
  release:
    types: [published]
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      tag:
        description: "image tag"
        required: true

jobs:
  build-and-push:
    strategy:
      fail-fast: false
      matrix:
        image: [stormpiper]
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare if manual dispatch
        id: prep_manual
        run: |
          DOCKER_IMAGE=gcr.io/stormpiper/${{ matrix.image }}
          TAGS=${DOCKER_IMAGE}:${{ github.event.inputs.tag }}
          echo "manual tags: ${TAGS}"
          echo ::set-output name=tags::${TAGS}

      - name: Prepare if auto tag
        id: prep_auto
        run: |
          DOCKER_IMAGE=gcr.io/stormpiper/${{ matrix.image }}
          VERSION=edge
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            TAGS="${TAGS},${DOCKER_IMAGE}:latest"
          fi
          echo "auto tags: ${TAGS}"
          echo ::set-output name=tags::${TAGS}

      - name: Prepare tag
        id: prep
        run: |
          TAGS=${{ steps.prep_auto.outputs.tags }}
          if [[ ${{ steps.prep_manual.outputs.tags }} ]]; then
            TAGS=${{ steps.prep_manual.outputs.tags }}
          fi
          echo "tags: ${TAGS}"
          echo ::set-output name=tags::${TAGS}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

      - name: Login to GCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          # file: ./Dockerfile
          target: ${{ matrix.image }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
