# This is a basic workflow to help you get started with Actions

name: Lint & Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches:
      - main
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - run: sudo apt-get install libspatialindex-dev unixodbc libpq-dev
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Linters
        run: |
          pip install -U pip
          pip install -r stormpiper/requirements.txt -r stormpiper/requirements_test.txt
      - name: Run Linters
        run: |
          bash scripts/lint.sh
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: docker-stack.yml
      COMPOSE_DOCKER_CLI_BUILD: 1

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: build stack
        run: |
          make stack
          docker-compose build stormpiper-test
          docker-compose up -d stormpiper-test

      - name: run tests
        run: make coverage-ci

      - name: coverage
        run: |
          docker-compose exec -T stormpiper-test coverage report -mi
          docker-compose exec -T stormpiper-test coverage xml
          docker-compose exec -T stormpiper-test cat coverage.xml > coverage.xml
          docker-compose exec -T stormpiper-test cat .coverage > .coverage

      - name: upload coverage
        uses: codecov/codecov-action@v1
